# Generated by Django 4.2.1 on 2023-08-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_name', models.CharField(max_length=100)),
                ('Princeple_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('School_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panda', to='app.school')),
            ],
        ),
    ]
